[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gstoolkit"
version = "0.0.1"
description = "All-in-one repository for state-of-the-art Gaussian Splatting"
readme = "README.md"
license = { text="MIT"}
requires-python = ">=3.8.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
]

# Dependencies
dependencies = [
    "torch",
    "tyro",
    "torchvision",
    "plyfile==0.8.1",
    "rich",
    "diff-gaussian-rasterization @ file:///home/user/gstoolkit/gs_toolkit/thrid_party/diff-gaussian-rasterization",
    "simple-knn @ file:///home/user/gstoolkit/gs_toolkit/thrid_party/simple-knn",
]

[project.optional-dependencies]
# Development dependencies
dev = [
    "black[jupyter]",
    "pre-commit",
    "pytest",
    "pytest-xdist",
    "typeguard",
    "ruff",
    "sshconfig",
]

[project.scripts]
gs-train = "gs_toolkit.scripts.train:entrypoint"
