[project]
name = "gstoolkit"
authors = [
    {name = "Hu Tianrun", email = "tianrunhu@gmail.com"},
]
version = "0.0.1"
description = "All-in-one repository for state-of-the-art Gaussian Splatting"
readme = "README.md"
license = { text="MIT"}
requires-python = ">=3.8.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
]

[tool.dependencies]
# Dependencies
dependencies = [
    "tyro",
    "torch",
    "torchvision",
    "plyfile==0.8.1",
    "rich",
    # "diff_gaussian_rasterization @ file:///workspace/thrid_party/diff-gaussian-rasterization",
    # "simple_knn @ file:///workspace/thrid_party/simple-knn",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
# Development dependencies
dev = [
    "black[jupyter]",
    "pre-commit",
    "pytest",
    "pytest-xdist",
    "typeguard",
    "ruff",
    "sshconfig",
]

[project.scripts]
gs-process-data = "gs_toolkit.scripts.process_data:entrypoint"
gs-train = "gs_toolkit.scripts.train:entrypoint"

[tool.setuptools.packages.find]
where = ["."]
include = ["gs_toolkit", "third_party/*"]
exclude = []
namespaces = false
