[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gstoolkit"
version = "0.0.1"
description = "All-in-one repository for state-of-the-art Gaussian Splatting"
readme = "README.md"
license = { text="Apache 2.0"}
requires-python = ">=3.8.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
]

# Dependencies
dependencies = [
    "torch",
    "torchvision",
]

[project.optional-dependencies]
# Development dependencies
dev = [
    "black[jupyter]",
    "pre-commit",
    "pytest",
    "pytest-xdist",
    "typeguard",
    "ruff",
    "sshconfig",
]
