version: "3.8"

services:
  gstoolkit:
    shm_size: '12gb'
    image: gstoolkit:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      PULSE_SERVER: $PULSE_SERVER
    ports:
      - "7007:7007"
    volumes:
      - ../:/workspace/
      - ../../../dataset/:/data/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - $HOME/.Xauthority:/home/user/.Xauthority:rw
      - $HOME/.ssh:/home/user/.ssh:rw
    working_dir: /workspace/
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
